/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx,js,jsx}"
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        ans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        headline: ['Newsreader', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Premium Editorial (Stitch-inspired) MD3 Palette
        "surface": "#131312",
        "surface-container": "#20201e",
        "surface-container-low": "#1c1c1a",
        "surface-container-high": "#2a2a28",
        "surface-container-highest": "#353532",
        "surface-container-lowest": "#0e0e0c",
        "surface-bright": "#3a3937",
        "surface-dim": "#131312",
        "surface-tint": "#ffb59e",
        "on-surface": "#e5e2de",
        "on-surface-variant": "#dbc1b9",
        "on-background": "#e5e2de",
        "primary-container": "#d97757",
        "on-primary-container": "#541400",
        "on-primary": "#5c1902",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#ffb59e",
        "on-primary-fixed": "#390b00",
        "on-primary-fixed-variant": "#7a2f15",
        "secondary-container": "#304f48",
        "on-secondary-container": "#9ebfb7",
        "on-secondary": "#163630",
        "secondary-fixed": "#c7eae1",
        "secondary-fixed-dim": "#accec5",
        "on-secondary-fixed": "#00201b",
        "on-secondary-fixed-variant": "#2d4c46",
        "tertiary": "#ffb3b2",
        "tertiary-container": "#d37878",
        "on-tertiary-container": "#531418",
        "on-tertiary": "#5a1a1d",
        "tertiary-fixed": "#ffdad8",
        "tertiary-fixed-dim": "#ffb3b2",
        "on-tertiary-fixed": "#3e040a",
        "on-tertiary-fixed-variant": "#772f31",
        "outline": "#a38c85",
        "outline-variant": "#55433d",
        "inverse-primary": "#99462a",
        "inverse-surface": "#e5e2de",
        "inverse-on-surface": "#31302e",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
