class NodeID:
    BUILDER          = "builder"
    SCHEMA_VALIDATOR = "schema_validator"
    BACKTEST_FULL    = "backtest_full"
    BACKTEST_QUICK   = "backtest_quick"
    DEBATE_BULL      = "debate_bull"
    DEBATE_BEAR      = "debate_bear"
    DEBATE_MODERATOR = "debate_moderator"
    FINDEBATE        = "findebate"
    SCENARIO_BATTERY = "scenario_battery"
    PROMOTION_GATE   = "promotion_gate"
    SENTINEL_DEPLOY  = "sentinel_deploy"
    SIGNAL_CARD      = "signal_card"
    INTAKE           = "intake"
